# fly.toml app configuration file generated for cicd-phonebook on 2025-07-24T12:07:44+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cicd-phonebook'
primary_region = 'arn'

[env]
  PORT = "3000"

[processes]
  app = "node index.cjs"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
